import React, { createContext, useState, useEffect, useContext } from 'react'
import axios from 'axios'
import { useAuth } from './AuthContext'

const SettingsContext = createContext()

export const THEME_COLORS = {
  red: '#ff3b30',
  orange: '#ff9500',
  yellow: '#ffcc00',
  green: '#34c759',
  blue: '#007AFF',
  purple: '#af52de',
  pink: '#ff2d55',
  cyan: '#5ac8fa'
}

// Названия цветов на разных языках
const THEME_COLOR_NAMES = {
  en: {
    red: 'Red',
    orange: 'Orange',
    yellow: 'Yellow',
    green: 'Green',
    blue: 'Blue',
    purple: 'Purple',
    pink: 'Pink',
    cyan: 'Cyan'
  },
  ru: {
    red: 'Красный',
    orange: 'Оранжевый',
    yellow: 'Жёлтый',
    green: 'Зелёный',
    blue: 'Синий',
    purple: 'Фиолетовый',
    pink: 'Розовый',
    cyan: 'Голубой'
  },
  tk: {
    red: 'Gyzyl',
    orange: 'Mämişi',
    yellow: 'Sary',
    green: 'Ýaşyl',
    blue: 'Gök',
    purple: 'Gyrmyzy',
    pink: 'Çal gyzyl',
    cyan: 'Mawy'
  },
  zh: {
    red: '红色',
    orange: '橙色',
    yellow: '黄色',
    green: '绿色',
    blue: '蓝色',
    purple: '紫色',
    pink: '粉色',
    cyan: '青色'
  }
}

const LANGUAGES = {
  en: 'English',
  ru: 'Русский',
  tk: 'Türkmençe',
  zh: '中文'
}

// Полные переводы интерфейса
const TRANSLATIONS = {
  en: {
    // Навигация
    learn: 'Learn',
    learnHubSub: 'Pick decks, set size, start',
    all: 'All',
    dictionary: 'Dictionary',
    myDictionaries: 'My Dictionaries',
    search: 'Search',
    lexiconNav: 'HSK',
    lexiconTitle: 'Lexicon',
    lexiconSubtitle: 'Official HSK 1–6 vocabulary — from basic to advanced',
    lexiconWords: 'words',
    lexiconPlaceholder: 'Hanzi, pinyin or meaning…',
    lexiconFind: 'Find',
    lexiconAllLevels: 'All levels',
    lexiconFound: 'Showing {count} words',
    lexiconKnown: 'Known',
    lexiconMarkKnown: 'Mark as known',
    lexiconHighlightUnique: 'Highlight unique characters',
    lexiconHideKnown: 'Hide known',
    lexiconGridHint: 'Tap a tile for details · Right‑click / long-press to mark known',
    translate: 'Translate',
    settings: 'Settings',
    profile: 'Profile',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    login: 'Login',

    // Лендинг
    appName: '好好学习: Chinese Language',
    heroTitle: '好好学习',
    heroSubtitle: 'Practice HSK Chinese vocabulary with flashcards.',
    heroDescription: '',
    productTagline: 'Chinese Language',
    lpEyebrow: 'Chinese HSK practice',
    lpLead:
      'This site helps you learn HSK words: characters, pinyin and meaning. Pick a deck, answer cards, make your own lists.',
    lpWhatTitle: 'What you get',
    lpWhat1Title: 'HSK 1–6 words',
    lpWhat1Text: 'About 5000 words from the HSK lists.',
    lpWhat2Title: 'Flashcard practice',
    lpWhat2Text: 'See a character or pinyin, choose the correct answer.',
    lpWhat3Title: 'Your own lists',
    lpWhat3Text: 'Save words and study only your decks.',
    lpHowTitle: 'How to use',
    lpHow1Title: 'Open Learn',
    lpHow1Text: 'Choose HSK level or your deck.',
    lpHow2Title: 'Set card count',
    lpHow2Text: '10, 20, 40 cards — or the whole list.',
    lpHow3Title: 'Practice',
    lpHow3Text: 'Answer cards. Mistakes can be reviewed later.',
    lpDemoLabel: 'Example card',
    lpDemoDef: 'to study · to learn',
    lpDemoCaption: 'Word on screen → pick the right answer',
    lpCtaTitle: 'Start practicing',
    lpCtaGuest: 'Register or log in, then open Learn.',
    lpCtaLoggedIn: 'Open Learn and pick a deck.',
    startLearning: 'Start learning',
    freeRegister: 'Register',
    features: 'Features',
    hskVocabulary: 'HSK 1–6 vocabulary',
    hskVocabularyDesc: 'Words for every HSK level',
    smartLearning: 'Practice modes',
    smartLearningDesc: 'Character ↔ pinyin and character ↔ meaning',
    customDictionary: 'Your decks',
    customDictionaryDesc: 'Build lists and study them',
    learningProgress: 'Mistakes',
    learningProgressDesc: 'Retry words you got wrong',
    dictionarySearch: 'HSK grid',
    dictionarySearchDesc: 'Browse HSK words on one screen',
    keyboardSupport: 'Keyboard',
    keyboardSupportDesc: 'Answer with keys 1–4 and Space',
    hotkeysMetaKeys: '1–4 / Space',
    hotkeysMetaLabel: 'hotkeys',
    hotkeysAnswers: 'answers',
    hotkeysSkip: 'skip',
    hotkeysEnd: 'end',
    dashToday: 'Today',
    dashCards: 'cards',
    dashStreak: 'Streak',
    dashBest: 'Best',
    dashAccuracy: 'Accuracy',
    dashSessions: 'Sessions',
    dashAnswered: 'Answered',
    dashWeek: 'Last 7 days',
    dashReviewMistakes: 'Review mistakes',
    dashRecent: 'Recent decks',
    dashDailyGoal: 'Daily goal (cards)',
    dashSubtitle: 'Daily practice & progress',
    dashQuickHsk: 'Quick HSK (20 cards)',
    dashBackToHome: 'Back to dashboard',
    dashNoMistakes: 'No mistakes to review',
    dashContinue: 'Continue last',
    sessionComplete: 'Session complete',
    sessionCorrect: 'Correct',
    sessionWrong: 'Wrong',
    sessionTotal: 'Total',
    sessionRetry: 'Try again',
    sessionRetryWrong: 'Retry mistakes',
    sessionHome: 'Back',
    sessionMistakes: 'Mistakes',
    showTranslation: 'Show meaning',
    showPinyin: 'Show pinyin',
    gradeGreat: 'Excellent',
    gradeGood: 'Good work',
    gradeOk: 'Keep going',
    gradeRetry: 'Review recommended',
    productTagline: 'Chinese Language',
    dictionaryEmpty: 'Dictionary has no words',
    pleaseLogin: 'Please log in',
    noWordsInSelection: 'No words in selected decks',
    more: 'More',
    accountHubSub: 'Account & preferences',
    accountProfileHint: 'Name and password',
    accountDictsHint: 'Your word lists and decks',
    accountSettingsHint: 'Theme, language, preferences',
    accountAdminHint: 'Users and moderation',
    backToAccount: 'Account',
    studyStats: 'Study stats',
    exportKnown: 'Export known IDs',
    clearKnown: 'Clear known',
    quickAddWord: 'Quick add word',
    textbookPacks: 'textbook packs',
    readyToStart: 'Ready to start learning? ',
    joinUs: 'Join us and start your Chinese learning journey',
    vocabulary: 'Vocabulary',
    hskLevels: 'HSK Levels',
    learningModes: 'Learning Modes',
    unlimitedDictionaries: 'Unlimited Dictionaries',

    // Словари
    words: 'words',
    createNewDictionary: 'Create New Dictionary',
    importDictionary: 'Import Dictionary',
    exportAsJSON: 'Export as JSON',
    exportAsCSV: 'Export as CSV',
    editDictionary: 'Edit Dictionary',
    deleteDictionary: 'Delete Dictionary',
    startLearningDict: 'Start Learning',
    actions: 'Actions',
    selectedWords: 'Selected Words',
    clearAll: 'Clear All',
    createFromSelected: 'Create from Selected',
    noDictionariesYet: 'No dictionaries yet',
    createYourFirst: 'Create your first dictionary or search for words to add them to a new dictionary.',
    goToSearch: 'Go to Dictionary Search',
    dictionaryName: 'Dictionary Name',

    // Настройки
    themeColor: 'Theme Color',
    language: 'Language',
    translationLanguages: 'Show translations in',
    selectTranslations: 'Select which translations to show when viewing word details',
    selectTranslationsDescription: 'Select which translations to show when viewing word details',
    save: 'Save',
    cancel: 'Cancel',
    settingsSaved: 'Settings saved! ',
    redirecting: 'Redirecting...',

    // Обучение
    correct: 'Correct',
    incorrect: 'Incorrect',
    finish: 'Finish',
    tryAgain: 'Try Again',
    retryIncorrect: 'Retry Incorrect',
    selectDictionary: 'Select Dictionary',
    learningMode: 'Learning Mode',

    // Поиск
    loading: 'Loading.. .',
    searching: 'Searching...',
    noResults: 'No results found',
    searchPlaceholder: 'Search for Chinese characters, pinyin, or English.. .',
    found: 'Found',
    results: 'result(s)',
    addToSelected: 'Add to Selected',
    viewDetails: 'View Details',

    // Общее
    home: 'Home',
    and: 'and',
    more: 'more',

    // Импорт
    format: 'Format',
    uploadFile: 'Upload File',
    orPasteContent: 'Or Paste Content',
    import: 'Import',
    jsonFormat: 'JSON Format',
    csvFormat: 'CSV Format',
    copy: 'Copy',

    // Слово деталь
    definition: 'Definition',
    strokeOrder: 'Stroke Order',
    exampleSentences: 'Example Sentences',
    loadingStrokeOrder: 'Loading stroke order...',
    strokeOrderNotAvailable: 'Stroke order animation not available',
    playPronunciation: 'Play pronunciation',
    loadingExamples: 'Loading examples...',
    noExamplesFound: 'No example sentences found',
    exampleSentencesTitle: 'Example Sentences',
    premium: 'PREMIUM',
    free: 'FREE',
    showAllExamples: 'Show all {count} examples ({more} more)',
    showLess: 'Show less',
    traditional: 'Traditional:',
    wordAddedToSelected: 'Word added to selected!',
    failedToAddWord: 'Failed to add word',
    tryDifferentSearch: 'Try searching with different characters, pinyin or English words',

    // Страница Learn/SettingsForm
    learningMode: 'Learning Mode',
    proTip: 'Pro tip: You can create your own custom dictionaries!',
    goToMyDictionaries: 'Go to My Dictionaries',
    selectVocabulary: 'Select Vocabulary (vocabularies do not overlap)',
    wordsLimit: 'Words Limit (0 = no limit)',
    modesDescription: 'Modes (if multiple selected, will switch randomly)',
    charactersToPinyin: 'Characters → Pinyin',
    pinyinToCharacters: 'Pinyin → Characters',
    charactersToTranslation: 'Characters → Translation',
    translationToCharacters: 'Translation → Characters',
    otherSettings: 'Other Settings',
    alwaysShowPinyin: 'Always show pinyin',
    alwaysShowDefinition: 'Always show definition',
    loadingDictionaries: 'Loading dictionaries...',
    dictionaryOrder: 'Dictionary Order (Drag to reorder):',
    dictionaryNotFound: 'Dictionary not found or empty',
    backToDictionaries: 'Back to Dictionaries',
    learning: 'Learning:',
    wordsCount: 'words',
    confirmDeleteDictionary: 'Are you sure you want to delete this dictionary?',
    dictionaryExported: 'Dictionary "{name}" exported as {format}',
    pleasePasteOrUpload: 'Please paste or upload file content',
    invalidJsonFormat: 'Invalid JSON format. Expected { name, words } or array of words.',
    noValidWordsFound: 'No valid words found in the file',
    importSuccess: 'Successfully imported {count} words!',
    failedToParseFile: 'Failed to parse file. Check the format.',
    andMore: '... and {count} more',
    failedToClearSelected: 'Failed to clear selected words:',
    editDictionaryTitle: 'Edit Dictionary: {name}',
    wordsLabel: 'Words',
    chineseCharacter: 'Chinese character',
    pinyinLabel: 'Pinyin',
    translationLabel: 'Translation',
    addWord: 'Add Word',
    updateDictionary: 'Update Dictionary',
    importDictionaryTitle: 'Import Dictionary',
    formatLabel: 'Format',
    uploadFile: 'Upload File',
    orPasteContent: 'Or Paste Content',
    importDictionaryBtn: 'Import Dictionary',
    cancel: 'Cancel',
    jsonFormatLabel: 'JSON Format:',
    jsonExampleCopied: 'JSON example copied!',
    copy: '📋 Copy',
    csvFormatLabel: 'CSV Format:',
    csvExampleCopied: 'CSV example copied!',
    dictionaryNamePlaceholder: 'My Chinese Words',
    yourNamePlaceholder: 'Your name',

    // Страница Dictionary
    selectVocabularyList: 'Select a list',
    dictAllLists: 'All lists',
    noPersonalDicts: 'No personal lists yet',

    // Страница Search
    searchPlaceholder: 'Search for Chinese characters, pinyin, or English translation...',

    // Страница Translate
    textTranslator: 'Text Translator',
    from: 'From',
    to: 'To',
    chinese: 'Chinese',
    russian: 'Russian',
    english: 'English',
    turkmen: 'Turkmen',
    enterTextToTranslate: 'Enter text to translate...',
    translationWillAppear: 'Translation will appear here...',
    useAITranslation: 'Use AI Translation (default)',

    // Системные уведомления
    passwordChanged: 'Password changed successfully',
    nameChanged: 'Name changed successfully',
    settingsSaved: 'Settings saved! ',
    error: 'Error',
    success: 'Success',
    somethingWentWrong: 'Something went wrong',
    pleaseWait: 'Please wait.. .',
    saved: 'Saved',
    deleted: 'Deleted',
    created: 'Created',
    updated: 'Updated',
    copied: 'Copied! ',
    failed: 'Failed',

    // Страница профиля
    profileSettings: 'Profile Settings',
    name: 'Name',
    email: 'Email',
    profileInformation: 'Profile Information',
    updateProfile: 'Update Profile',
    updating: 'Updating...',
    changePassword: 'Change Password',
    changing: 'Changing...',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    recentSearchHistory: 'Recent Search History',
    youAreAdmin: 'You are an administrator',
    youHavePremium: 'You have an active premium subscription',
    expires: 'expires',
    dictionaryNameRequired: 'Dictionary name is required',
    dictionaryCreated: 'Dictionary created successfully',
    dictionaryUpdated: 'Dictionary updated successfully',
    dictionaryDeleted: 'Dictionary deleted successfully',
    dictionaryFromSelected: 'Dictionary created from selected words!',
    failedCreateDictionary: 'Failed to create dictionary',
    noWordsSelected: 'No words selected',
    enterDictionaryName: 'Enter dictionary name:',

    // Админ панель
    adminPanelTitle: 'Admin Panel',
    usersManagement: 'Users Management',
    showAllUsers: 'Show All Users',
    onlineNow: 'Online Now',
    tableId: 'ID',
    tableName: 'Name',
    tableEmail: 'Email',
    tableStatus: 'Status',
    tablePremium: 'Premium',
    tableAdmin: 'Admin',
    tableIpAddress: 'IP Address',
    tableLastSeen: 'Last Seen',
    tableActions: 'Actions',
    statusBanned: 'Banned',
    statusOnline: 'Online',
    statusOffline: 'Offline',
    statusNever: 'Never',
    statusYes: 'Yes',
    statusNo: 'No',
    statusUnknown: 'Unknown',
    btnEdit: 'Edit',
    btnUnban: 'Unban',
    btnBan: 'Ban',
    btnDelete: 'Delete',
    modalEditUser: 'Edit User',
    userInfo: 'User Info',
    premiumUser: 'Premium User',
    premiumExpiresAt: 'Premium Expires At',
    adminUser: 'Admin User',
    bannedUser: 'Banned User',
    banReason: 'Ban Reason',
    placeholderBanReason: 'Reason for ban',
    btnUpdateUser: 'Update User',
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    promptBanReason: 'Enter ban reason:',
    userUpdated: 'User updated successfully',
    failedUpdateUser: 'Failed to update user',
    failedDeleteUser: 'Failed to delete user',
    userBanned: 'User banned successfully',
    failedBanUser: 'Failed to ban user',
    userUnbanned: 'User unbanned successfully',
    failedUnbanUser: 'Failed to unban user',
    unknown: 'Unknown',
    loadingText: 'Loading...',

    // Компонент SearchResults
    noResultsFound: 'No results found for',
    foundResults: 'Found',
    results: 'result(s)',
    addToSelected: 'Add to Selected',
    viewDetails: 'View Details',
    addToSelectedWords: 'Add to Selected Words',
    definition: 'Definition',
    strokeOrder: 'Stroke Order',
    exampleSentences: 'Example Sentences',
    loadingStrokeOrder: 'Loading stroke order...',
    strokeOrderNotAvailable: 'Stroke order animation not available',
    playPronunciation: 'Play pronunciation',
    loadingExamples: 'Loading examples...',
    noExamplesFound: 'No example sentences found',
    exampleSentencesTitle: 'Example Sentences',
    premium: 'PREMIUM',
    free: 'FREE',
    showAllExamples: 'Show all {count} examples ({more} more)',
    showLess: 'Show less',
    tryDifferentSearch: 'Try searching with different characters, pinyin or English words',
    traditional: 'Traditional:',
    loadingPinyin: 'Loading...',
    wordAddedToSelected: 'Word added to selected!',
    failedToAddWord: 'Failed to add word'
  },
  ru: {
    // Навигация
    learn: 'Учить',
    learnHubSub: 'Выбери колоду, размер — и старт',
    all: 'Все',
    dictionary: 'Словарь',
    myDictionaries: 'Мои словари',
    search: 'Поиск',
    lexiconNav: 'HSK',
    lexiconTitle: 'Словарь HSK',
    lexiconSubtitle: 'Официальная лексика HSK 1–6 — от простых слов к сложным',
    lexiconWords: 'слов',
    lexiconPlaceholder: 'Иероглиф, пиньинь или значение…',
    lexiconFind: 'Найти',
    lexiconAllLevels: 'Все уровни',
    lexiconFound: 'Показано {count} слов',
    lexiconKnown: 'Знаю',
    lexiconMarkKnown: 'Отметить «знаю»',
    lexiconHighlightUnique: 'Подсветить уникальные иероглифы',
    lexiconHideKnown: 'Скрыть «знаю»',
    lexiconGridHint: 'Нажми на плитку — детали · ПКМ — отметить «знаю»',
    translate: 'Перевод',
    settings: 'Настройки',
    profile: 'Профиль',
    adminPanel: 'Админ панель',
    logout: 'Выход',
    login: 'Войти',

    // Лендинг
    appName: '好好学习: Chinese Language',
    heroTitle: '好好学习',
    heroSubtitle: 'Тренируй слова HSK: иероглиф, пиньинь, перевод.',
    heroDescription: '',
    productTagline: 'Chinese Language',
    lpEyebrow: 'Сайт для слов HSK',
    lpLead:
      'Здесь учат китайские слова по HSK. Выбираешь колоду, отвечаешь на карточки, собираешь свои списки.',
    lpWhatTitle: 'Что есть на сайте',
    lpWhat1Title: 'Слова HSK 1–6',
    lpWhat1Text: 'Около 5000 слов из списков HSK.',
    lpWhat2Title: 'Карточки',
    lpWhat2Text: 'Видишь иероглиф или пиньинь — выбираешь правильный ответ.',
    lpWhat3Title: 'Свои словари',
    lpWhat3Text: 'Сохраняешь слова и учишь только нужное.',
    lpHowTitle: 'Как пользоваться',
    lpHow1Title: 'Открой «Учить»',
    lpHow1Text: 'Выбери уровень HSK или свой список.',
    lpHow2Title: 'Сколько карточек',
    lpHow2Text: '10, 20, 40 или весь список.',
    lpHow3Title: 'Отвечай',
    lpHow3Text: 'Ошибки можно потом повторить.',
    lpDemoLabel: 'Пример карточки',
    lpDemoDef: 'учить · учиться',
    lpDemoCaption: 'Слово на экране → выбираешь ответ',
    lpCtaTitle: 'Начать',
    lpCtaGuest: 'Зарегистрируйся или войди — потом открой «Учить».',
    lpCtaLoggedIn: 'Открой «Учить» и выбери колоду.',
    startLearning: 'Начать обучение',
    freeRegister: 'Регистрация',
    features: 'Что внутри',
    hskVocabulary: 'Словарь HSK 1–6',
    hskVocabularyDesc: 'Слова для каждого уровня HSK',
    smartLearning: 'Режимы тренировки',
    smartLearningDesc: 'Иероглиф ↔ пиньинь и иероглиф ↔ перевод',
    customDictionary: 'Свои колоды',
    customDictionaryDesc: 'Свои списки слов',
    learningProgress: 'Ошибки',
    learningProgressDesc: 'Повтор слов, где ошибся',
    dictionarySearch: 'Сетка HSK',
    dictionarySearchDesc: 'Все слова HSK на одном экране',
    keyboardSupport: 'Клавиатура',
    keyboardSupportDesc: 'Ответы клавишами 1–4 и Пробел',
    hotkeysMetaKeys: '1–4 / Пробел',
    hotkeysMetaLabel: 'горячие клавиши',
    hotkeysAnswers: 'ответы',
    hotkeysSkip: 'пропуск',
    hotkeysEnd: 'конец',
    dashToday: 'Сегодня',
    dashCards: 'карточек',
    dashStreak: 'Серия',
    dashBest: 'Рекорд',
    dashAccuracy: 'Точность',
    dashSessions: 'Сессии',
    dashAnswered: 'Ответов',
    dashWeek: '7 дней',
    dashReviewMistakes: 'Повторить ошибки',
    dashRecent: 'Недавние колоды',
    dashDailyGoal: 'Цель на день (карточки)',
    dashSubtitle: 'Практика и прогресс',
    dashQuickHsk: 'Быстрый HSK (20 карт)',
    dashBackToHome: 'К дашборду',
    dashNoMistakes: 'Нет ошибок для повторения',
    dashContinue: 'Продолжить',
    sessionComplete: 'Сессия завершена',
    sessionCorrect: 'Верно',
    sessionWrong: 'Ошибки',
    sessionTotal: 'Всего',
    sessionRetry: 'Ещё раз',
    sessionRetryWrong: 'Только ошибки',
    sessionHome: 'Назад',
    sessionMistakes: 'Ошибки',
    showTranslation: 'Показать перевод',
    showPinyin: 'Показать пиньинь',
    gradeGreat: 'Отлично',
    gradeGood: 'Хорошая работа',
    gradeOk: 'Продолжай',
    gradeRetry: 'Стоит повторить',
    productTagline: 'Chinese Language',
    dictionaryEmpty: 'В словаре нет слов',
    pleaseLogin: 'Войдите в аккаунт',
    noWordsInSelection: 'В выбранных колодах нет слов',
    more: 'Ещё',
    accountHubSub: 'Аккаунт и настройки',
    accountProfileHint: 'Имя и пароль',
    accountDictsHint: 'Ваши списки и колоды',
    accountSettingsHint: 'Тема, язык, предпочтения',
    accountAdminHint: 'Пользователи и модерация',
    backToAccount: 'Аккаунт',
    studyStats: 'Статистика',
    exportKnown: 'Экспорт «знаю»',
    clearKnown: 'Сбросить «знаю»',
    quickAddWord: 'Быстро добавить слово',
    textbookPacks: 'учебные наборы',
    readyToStart: 'Готовы начать обучение?',
    joinUs: 'Присоединяйтесь и начните свой путь изучения китайского',
    vocabulary: 'Словарный запас',
    hskLevels: 'Уровней HSK',
    learningModes: 'Режимов обучения',
    unlimitedDictionaries: 'Безлимит словарей',

    // Словари
    words: 'слов',
    createNewDictionary: 'Создать словарь',
    importDictionary: 'Импорт словаря',
    exportAsJSON: 'Экспорт JSON',
    exportAsCSV: 'Экспорт CSV',
    editDictionary: 'Редактировать',
    deleteDictionary: 'Удалить словарь',
    startLearningDict: 'Начать обучение',
    actions: 'Действия',
    selectedWords: 'Выбранные слова',
    clearAll: 'Очистить все',
    createFromSelected: 'Создать из выбранных',
    noDictionariesYet: 'Словарей пока нет',
    createYourFirst: 'Создайте свой первый словарь или найдите слова для добавления.',
    goToSearch: 'Перейти к поиску',
    dictionaryName: 'Название словаря',

    // Настройки
    themeColor: 'Цвет темы',
    language: 'Язык',
    translationLanguages: 'Показывать переводы на',
    selectTranslations: 'Выберите языки для отображения переводов',
    selectTranslationsDescription: 'Выберите языки для отображения переводов при просмотре деталей слова',
    save: 'Сохранить',
    cancel: 'Отмена',
    settingsSaved: 'Настройки сохранены! ',
    redirecting: 'Перенаправление...',

    // Обучение
    correct: 'Правильно',
    incorrect: 'Неправильно',
    finish: 'Завершить',
    tryAgain: 'Заново',
    retryIncorrect: 'Повторить ошибки',
    selectDictionary: 'Выбрать словарь',
    learningMode: 'Режим обучения',

    // Поиск
    loading: 'Загрузка.. .',
    searching: 'Поиск...',
    noResults: 'Ничего не найдено',
    searchPlaceholder: 'Поиск по иероглифам, пиньинь или переводу.. .',
    found: 'Найдено',
    results: 'результат(ов)',
    addToSelected: 'Добавить в выбранные',
    viewDetails: 'Подробнее',

    // Общее
    home: 'Главная',
    and: 'и',
    more: 'ещё',

    // Импорт
    format: 'Формат',
    uploadFile: 'Загрузить файл',
    orPasteContent: 'Или вставьте содержимое',
    import: 'Импортировать',
    jsonFormat: 'JSON формат',
    csvFormat: 'CSV формат',
    copy: 'Копировать',

    // Слово деталь
    definition: 'Определение',
    strokeOrder: 'Порядок штрихов',
    exampleSentences: 'Примеры предложений',
    loadingStrokeOrder: 'Загрузка порядка штрихов...',
    strokeOrderNotAvailable: 'Анимация порядка штрихов недоступна',
    playPronunciation: 'Произнести',
    loadingExamples: 'Загрузка примеров...',
    noExamplesFound: 'Примеры предложений не найдены',
    exampleSentencesTitle: 'Примеры предложений',
    premium: 'ПРЕМИУМ',
    free: 'БЕСПЛАТНО',
    showAllExamples: 'Показать все {count} примеров (ещё {more})',
    showLess: 'Показать меньше',
    traditional: 'Традиционное:',
    wordAddedToSelected: 'Слово добавлено в выбранные!',
    failedToAddWord: 'Не удалось добавить слово',
    tryDifferentSearch: 'Попробуйте искать с другими иероглифами, пиньинь или английскими словами',

    // Страница Learn/SettingsForm
    learningMode: 'Режим обучения',
    proTip: 'Подсказка: Вы можете создавать свои собственные словари!',
    goToMyDictionaries: 'Перейти к моим словарям',
    selectVocabulary: 'Выберите словарь (словари не пересекаются)',
    wordsLimit: 'Лимит слов (0 = без лимита)',
    modesDescription: 'Режимы (при выборе нескольких будут чередоваться случайно)',
    charactersToPinyin: 'Иероглифы → Пиньинь',
    pinyinToCharacters: 'Пиньинь → Иероглифы',
    charactersToTranslation: 'Иероглифы → Перевод',
    translationToCharacters: 'Перевод → Иероглифы',
    otherSettings: 'Другие настройки',
    alwaysShowPinyin: 'Всегда показывать пиньинь',
    alwaysShowDefinition: 'Всегда показывать значение',
    loadingDictionaries: 'Загрузка словарей...',
    dictionaryOrder: 'Порядок словарей (перетащите для изменения):',
    dictionaryNotFound: 'Словарь не найден или пуст',
    backToDictionaries: 'Вернуться к словарям',
    learning: 'Обучение:',
    wordsCount: 'слов',
    confirmDeleteDictionary: 'Вы уверены, что хотите удалить этот словарь?',
    dictionaryExported: 'Словарь "{name}" экспортирован как {format}',
    pleasePasteOrUpload: 'Пожалуйста, вставьте или загрузите содержимое файла',
    invalidJsonFormat: 'Неверный формат JSON. Ожидается { name, words } или массив слов.',
    noValidWordsFound: 'В файле не найдено допустимых слов',
    importSuccess: 'Успешно импортировано {count} слов!',
    failedToParseFile: 'Не удалось разобрать файл. Проверьте формат.',
    andMore: '... и ещё {count}',
    failedToClearSelected: 'Не удалось очистить выбранные слова:',
    editDictionaryTitle: 'Редактировать словарь: {name}',
    wordsLabel: 'Слова',
    chineseCharacter: 'Китайский иероглиф',
    pinyinLabel: 'Пиньинь',
    translationLabel: 'Перевод',
    addWord: 'Добавить слово',
    updateDictionary: 'Обновить словарь',
    importDictionaryTitle: 'Импорт словаря',
    formatLabel: 'Формат',
    uploadFile: 'Загрузить файл',
    orPasteContent: 'Или вставить содержимое',
    importDictionaryBtn: 'Импортировать словарь',
    cancel: 'Отмена',
    jsonFormatLabel: 'JSON формат:',
    jsonExampleCopied: 'Пример JSON скопирован!',
    copy: '📋 Копировать',
    csvFormatLabel: 'CSV формат:',
    csvExampleCopied: 'Пример CSV скопирован!',
    dictionaryNamePlaceholder: 'Мои китайские слова',
    yourNamePlaceholder: 'Ваше имя',

    // Страница Dictionary
    selectVocabularyList: 'Выберите список',
    dictAllLists: 'Все списки',
    noPersonalDicts: 'Пока нет своих словарей',

    // Страница Search
    searchPlaceholder: 'Поиск по иероглифам, пиньинь или переводу...',

    // Страница Translate
    textTranslator: 'Переводчик текста',
    from: 'С',
    to: 'На',
    chinese: 'Китайский',
    russian: 'Русский',
    english: 'Английский',
    turkmen: 'Туркменский',
    enterTextToTranslate: 'Введите текст для перевода...',
    translationWillAppear: 'Перевод появится здесь.. .',
    useAITranslation: 'Использовать ИИ перевод (по умолчанию)',

    // Системные уведомления
    passwordChanged: 'Пароль успешно изменён',
    nameChanged: 'Имя успешно изменено',
    settingsSaved: 'Настройки сохранены!',
    error: 'Ошибка',
    success: 'Успешно',
    somethingWentWrong: 'Что-то пошло не так',
    pleaseWait: 'Пожалуйста, подождите...',
    saved: 'Сохранено',
    deleted: 'Удалено',
    created: 'Создано',
    updated: 'Обновлено',
    copied: 'Скопировано!',
    failed: 'Ошибка',

    // Страница профиля
    profileSettings: 'Настройки профиля',
    name: 'Имя',
    email: 'Email',
    profileInformation: 'Информация профиля',
    updateProfile: 'Обновить профиль',
    updating: 'Обновление...',
    changePassword: 'Изменить пароль',
    changing: 'Изменение...',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmNewPassword: 'Подтвердить новый пароль',
    recentSearchHistory: 'История недавних поисков',
    youAreAdmin: 'Вы администратор',
    youHavePremium: 'У вас активная премиум-подписка',
    expires: 'истекает',
    dictionaryNameRequired: 'Название словаря обязательно',
    dictionaryCreated: 'Словарь успешно создан',
    dictionaryUpdated: 'Словарь успешно обновлен',
    dictionaryDeleted: 'Словарь успешно удален',
    dictionaryFromSelected: 'Словарь создан из выбранных слов!',
    failedCreateDictionary: 'Не удалось создать словарь',
    noWordsSelected: 'Не выбрано ни одного слова',
    enterDictionaryName: 'Введите название словаря:',

    // Админ панель
    adminPanelTitle: 'Админ панель',
    usersManagement: 'Управление пользователями',
    showAllUsers: 'Показать всех пользователей',
    onlineNow: 'Сейчас онлайн',
    tableId: 'ID',
    tableName: 'Имя',
    tableEmail: 'Email',
    tableStatus: 'Статус',
    tablePremium: 'Премиум',
    tableAdmin: 'Админ',
    tableIpAddress: 'IP адрес',
    tableLastSeen: 'Последний визит',
    tableActions: 'Действия',
    statusBanned: 'Заблокирован',
    statusOnline: 'Онлайн',
    statusOffline: 'Оффлайн',
    statusNever: 'Никогда',
    statusYes: 'Да',
    statusNo: 'Нет',
    statusUnknown: 'Неизвестно',
    btnEdit: 'Редактировать',
    btnUnban: 'Разблокировать',
    btnBan: 'Заблокировать',
    btnDelete: 'Удалить',
    modalEditUser: 'Редактировать пользователя',
    userInfo: 'Информация о пользователе',
    premiumUser: 'Премиум пользователь',
    premiumExpiresAt: 'Премиум истекает',
    adminUser: 'Администратор',
    bannedUser: 'Заблокированный пользователь',
    banReason: 'Причина блокировки',
    placeholderBanReason: 'Причина блокировки',
    btnUpdateUser: 'Обновить пользователя',
    confirmDeleteUser: 'Вы уверены, что хотите удалить этого пользователя?',
    promptBanReason: 'Введите причину блокировки:',
    userUpdated: 'Пользователь успешно обновлен',
    failedUpdateUser: 'Не удалось обновить пользователя',
    failedDeleteUser: 'Не удалось удалить пользователя',
    userBanned: 'Пользователь заблокирован',
    failedBanUser: 'Не удалось заблокировать пользователя',
    userUnbanned: 'Пользователь разблокирован',
    failedUnbanUser: 'Не удалось разблокировать пользователя',
    unknown: 'Неизвестно',
    loadingText: 'Загрузка...',

    // Компонент SearchResults
    noResultsFound: 'Ничего не найдено для',
    foundResults: 'Найдено',
    results: 'результат(ов)',
    addToSelected: 'Добавить в выбранные',
    viewDetails: 'Подробнее',
    addToSelectedWords: 'Добавить в выбранные слова',
    definition: 'Определение',
    strokeOrder: 'Порядок штрихов',
    exampleSentences: 'Примеры предложений',
    loadingStrokeOrder: 'Загрузка порядка штрихов...',
    strokeOrderNotAvailable: 'Анимация порядка штрихов недоступна',
    playPronunciation: 'Произнести',
    loadingExamples: 'Загрузка примеров...',
    noExamplesFound: 'Примеры предложений не найдены',
    exampleSentencesTitle: 'Примеры предложений',
    premium: 'ПРЕМИУМ',
    free: 'БЕСПЛАТНО',
    showAllExamples: 'Показать все {count} примеров (ещё {more})',
    showLess: 'Показать меньше',
    tryDifferentSearch: 'Попробуйте искать с другими иероглифами, пиньинь или английскими словами',
    traditional: 'Традиционное:',
    loadingPinyin: 'Загрузка...',
    wordAddedToSelected: 'Слово добавлено в выбранные!',
    failedToAddWord: 'Не удалось добавить слово'
  },
  tk: {
    // Навигация
    learn: 'Öwren',
    dictionary: 'Sözlük',
    myDictionaries: 'Meniň sözlüklerim',
    search: 'Gözle',
    lexiconNav: 'HSK',
    lexiconTitle: 'HSK sözlük',
    lexiconSubtitle: 'Resmi HSK 1–6 leksikasy — esasy sözlerden çylşyrymlylara',
    lexiconWords: 'söz',
    lexiconPlaceholder: 'Nyşan, pinyin ýa-da many…',
    lexiconFind: 'Tap',
    lexiconAllLevels: 'Ähli derejeler',
    lexiconFound: '{count} söz görkezilýär',
    lexiconKnown: 'Bilýän',
    lexiconMarkKnown: '«Bilýän» diýip belle',
    lexiconHighlightUnique: 'Üýtgeşik nyşanlary bellä',
    lexiconGridHint: 'Jikme-jiklik üçin bas · «Bilýän» üçin sag knopka',
    translate: 'Terjime',
    settings: 'Sazlamalar',
    profile: 'Profil',
    adminPanel: 'Admin paneli',
    logout: 'Çykmak',
    login: 'Girmek',

    // Лендинг
    appName: '好好学习: Chinese Language',
    heroTitle: '好好学习',
    heroSubtitle: 'Chinese Language — HSK sözlük platformasy',
    heroDescription: 'HSK1-den HSK6-a çenli 5000+ hytaý sözüni öwren',
    productTagline: 'Chinese Language',
    startLearning: 'Öwrenmäge başla',
    freeRegister: 'Hasap aç',
    features: 'Aýratynlyklar',
    hskVocabulary: 'HSK 1-6 Sözlük',
    hskVocabularyDesc: 'Ähli HSK derejeler üçin doly sözlük',
    smartLearning: 'Akylly öwreniş',
    smartLearningDesc: 'Köp öwreniş usullary',
    customDictionary: 'Öz sözlük',
    customDictionaryDesc: 'Öz söz sanawlaryňyzy dörediň',
    learningProgress: 'Öwreniş ösüşi',
    learningProgressDesc: 'Ösüşiňizi yzarlaň',
    dictionarySearch: 'Sözlük gözlegi',
    dictionarySearchDesc: 'Islendik nyşan, pinyin ýa-da terjime gözläň',
    keyboardSupport: 'Klawiatura goldawy',
    keyboardSupportDesc: 'Çalt jogap bermek üçin klawiaturany ulanyň',
    hotkeysMetaKeys: '1–4 / Boşluk',
    hotkeysMetaLabel: 'gyzgytlar',
    hotkeysAnswers: 'jogaplar',
    hotkeysSkip: 'geç',
    hotkeysEnd: 'soň',
    dashToday: 'Şu gün',
    dashCards: 'kart',
    dashStreak: 'Yzygiderlilik',
    dashBest: 'Iň gowy',
    dashAccuracy: 'Takyklyk',
    dashSessions: 'Sessiýalar',
    dashAnswered: 'Jogaplar',
    dashWeek: '7 gün',
    dashReviewMistakes: 'Ýalňyşlyklary gaýtala',
    dashRecent: 'Soňky kolodalar',
    dashDailyGoal: 'Gündelik maksat',
    dashSubtitle: 'Gündelik praktika',
    dashQuickHsk: 'Çalt HSK (20 kart)',
    dashBackToHome: 'Dashboard',
    dashNoMistakes: 'Ýalňyşlyk ýok',
    sessionComplete: 'Sessiýa tamam',
    sessionCorrect: 'Dogry',
    sessionWrong: 'Ýalňyş',
    sessionTotal: 'Jemi',
    sessionRetry: 'Täzeden',
    sessionRetryWrong: 'Diňe ýalňyşlar',
    sessionHome: 'Yza',
    sessionMistakes: 'Ýalňyşlyklar',
    dictionaryEmpty: 'Sözlük boş',
    pleaseLogin: 'Giriş ediň',
    noWordsInSelection: 'Söz ýok',
    more: 'Has köp',
    accountHubSub: 'Hasap we sazlamalar',
    accountProfileHint: 'At we parol',
    accountDictsHint: 'Siziň listleriňiz',
    accountSettingsHint: 'Tema, dil, sazlamalar',
    accountAdminHint: 'Ulanyjylar',
    backToAccount: 'Hasap',
    studyStats: 'Statistika',
    exportKnown: 'Bilenleri eksport',
    clearKnown: 'Bilenleri arassala',
    readyToStart: 'Öwrenmäge taýynmy?',
    joinUs: 'Bize goşulyň we hytaý dili syýahatyňyzy başlaň',
    vocabulary: 'Sözlük',
    hskLevels: 'HSK derejesi',
    learningModes: 'Öwreniş usullary',
    unlimitedDictionaries: 'Çäksiz sözlükler',

    // Словари
    words: 'söz',
    createNewDictionary: 'Täze sözlük döret',
    importDictionary: 'Sözlük import et',
    exportAsJSON: 'JSON eksport',
    exportAsCSV: 'CSV eksport',
    editDictionary: 'Üýtget',
    deleteDictionary: 'Poz',
    startLearningDict: 'Öwrenmäge başla',
    actions: 'Hereketler',
    selectedWords: 'Saýlanan sözler',
    clearAll: 'Hemmesini arassala',
    createFromSelected: 'Saýlananlardan döret',
    noDictionariesYet: 'Entek sözlük ýok',
    createYourFirst: 'Ilkinji sözlügiňizi dörediň.',
    goToSearch: 'Gözlege git',
    dictionaryName: 'Sözlük ady',

    // Настройки
    themeColor: 'Tema reňki',
    language: 'Dil',
    translationLanguages: 'Terjimeleri görkez',
    selectTranslations: 'Terjime dillerini saýlaň',
    selectTranslationsDescription: 'Söz jikme-jikliklerini göreniňizde görkeziljek terjime dillerini saýlaň',
    save: 'Sakla',
    cancel: 'Ýatyr',
    settingsSaved: 'Sazlamalar saklandy!',
    redirecting: 'Ugratylýar...',

    // Обучение
    correct: 'Dogry',
    incorrect: 'Ýalňyş',
    finish: 'Gutarmak',
    tryAgain: 'Täzeden',
    retryIncorrect: 'Ýalňyşlary gaýtala',
    selectDictionary: 'Sözlük saýla',
    learningMode: 'Öwreniş usuly',

    // Поиск
    loading: 'Ýüklenýär...',
    searching: 'Gözlenýär...',
    noResults: 'Netije tapylmady',
    searchPlaceholder: 'Hytaý harplary, pinyin ýa-da terjime boýunça gözle.. .',
    found: 'Tapyldy',
    results: 'netije',
    addToSelected: 'Saýlananlara goş',
    viewDetails: 'Jikme-jiklik',

    // Общее
    home: 'Baş sahypa',
    and: 'we',
    more: 'köp',

    // Импорт
    format: 'Format',
    uploadFile: 'Faýl ýükle',
    orPasteContent: 'Ýa-da mazmuny goý',
    import: 'Import et',
    jsonFormat: 'JSON format',
    csvFormat: 'CSV format',
    copy: 'Göçür',

    // Слово деталь
    definition: 'Kesgitleme',
    strokeOrder: 'Çyzgy tertibi',
    exampleSentences: 'Mysal sözlemler',
    loadingStrokeOrder: 'Çyzgy tertibini ýüklenýär...',
    strokeOrderNotAvailable: 'Çyzgy tertibi animasiýasy elýeter däl',
    playPronunciation: 'Aýdyň oka',
    loadingExamples: 'Mysallary ýüklenýär...',
    noExamplesFound: 'Mysal sözlemler tapylmady',
    exampleSentencesTitle: 'Mysal sözlemler',
    premium: 'PREMIÝA',
    free: 'MUGT',
    showAllExamples: 'Ähli {count} mysaly görkez ({more} sany köp)',
    showLess: 'Az görkez',
    traditional: 'Köneş:',
    wordAddedToSelected: 'Söz saýlananlara goşuldy!',
    failedToAddWord: 'Söz goşup bolmady',
    tryDifferentSearch: 'Başga nyşanlar, pinyin ýa-da iňlis sözleri bilen gözläň',

    // Страница Learn/SettingsForm
    learningMode: 'Öwreniş usuly',
    proTip: 'Maslahat: Öz sözlükleriňizi döredip bilersiňiz!',
    goToMyDictionaries: 'Meniň sözlüklerime git',
    selectVocabulary: 'Sözlük saýlaň (sözlükler gaýtalanmaýar)',
    wordsLimit: 'Söz çäklendirmesi (0 = çäksiz)',
    modesDescription: 'Usullar (köp saýlansa, tötänleýin çalyşýar)',
    charactersToPinyin: 'Nyşanlar → Pinyin',
    pinyinToCharacters: 'Pinyin → Nyşanlar',
    charactersToTranslation: 'Nyşanlar → Terjime',
    translationToCharacters: 'Terjime → Nyşanlar',
    otherSettings: 'Beýleki sazlamalar',
    alwaysShowPinyin: 'Hemişe pinyin görkez',
    alwaysShowDefinition: 'Hemişe manysy görkez',
    loadingDictionaries: 'Sözlükler ýüklenýär...',
    dictionaryOrder: 'Sözlük tertibi (çekip üýtgetmek üçin):',
    dictionaryNotFound: 'Sözlük tapylmady ýa-da boş',
    backToDictionaries: 'Sözlüklere yza gaýt',
    learning: 'Öwreniş:',
    wordsCount: 'söz',
    confirmDeleteDictionary: 'Bu sözlügi pozmak isleýändigiňize ynanýarsyňyzmy?',
    dictionaryExported: 'Sözlük "{name}" {format} hökmünde eksport edildi',
    pleasePasteOrUpload: 'Faýl mazmunyny goýuň ýa-da ýükleň',
    invalidJsonFormat: 'Nädogry JSON format. { name, words } ýa-da sözleriň massiwy garaşylýar.',
    noValidWordsFound: 'Faýlda kabul edilýän sözler tapylmady',
    importSuccess: '{count} söz üstünlikli import edildi!',
    failedToParseFile: 'Faýly pars etmek başa barmady. Format barlaň.',
    andMore: '... we {count} sany köp',
    failedToClearSelected: 'Saýlanan sözleri arassalamak başa barmady:',
    editDictionaryTitle: 'Sözlügi üýtget: {name}',
    wordsLabel: 'Sözler',
    chineseCharacter: 'Hytaý nyşany',
    pinyinLabel: 'Pinyin',
    translationLabel: 'Terjime',
    addWord: 'Söz goş',
    updateDictionary: 'Sözlügi täzele',
    importDictionaryTitle: '📥 Sözlük import et',
    formatLabel: 'Format',
    uploadFile: 'Faýl ýükle',
    orPasteContent: 'Ýa-da mazmuny goý',
    importDictionaryBtn: 'Sözlük import et',
    cancel: 'Ýatyr',
    jsonFormatLabel: 'JSON format:',
    jsonExampleCopied: 'JSON mysaly göçürildi!',
    copy: '📋 Göçür',
    csvFormatLabel: 'CSV format:',
    csvExampleCopied: 'CSV mysaly göçürildi!',
    dictionaryNamePlaceholder: 'Meniň hytaý sözlerim',
    yourNamePlaceholder: 'Siziň adyňyz',

    // Страница Dictionary
    selectVocabularyList: 'Sözlük saýlaň',

    // Страница Search
    searchPlaceholder: 'Hytaý harplary, pinyin ýa-da terjime boýunça gözle...',

    // Страница Translate
    textTranslator: 'Tekst terjimeçisi',
    from: '-dan',
    to: '-a',
    chinese: 'Hytaýça',
    russian: 'Rusça',
    english: 'Iňlisçe',
    turkmen: 'Türkmençe',
    enterTextToTranslate: 'Terjime üçin tekst giriziň...',
    translationWillAppear: 'Terjime şu ýerde görkeziler...',
    useAITranslation: 'AI terjimesini ulan (deslapky)',

    // Системные уведомления
    passwordChanged: 'Parol üstünlikli üýtgedildi',
    nameChanged: 'At üstünlikli üýtgedildi',
    settingsSaved: 'Sazlamalar saklandy!',
    error: 'Ýalňyşlyk',
    success: 'Üstünlik',
    somethingWentWrong: 'Bir zat ýalňyş gitdi',
    pleaseWait: 'Garaşyň.. .',
    saved: 'Saklandy',
    deleted: 'Öçürildi',
    created: 'Döredildi',
    updated: 'Täzelendi',
    copied: 'Göçürildi!',
    failed: 'Şowsuz',

    // Страница профиля
    profileSettings: 'Profil sazlamalary',
    name: 'At',
    email: 'Email',
    profileInformation: 'Profil maglumatlary',
    updateProfile: 'Profil üýtget',
    updating: 'Üýtgedilýär...',
    changePassword: 'Parol üýtget',
    changing: 'Üýtgedilýär...',
    currentPassword: 'Häzirki parol',
    newPassword: 'Täze parol',
    confirmNewPassword: 'Täze paroly tassykla',
    recentSearchHistory: 'Ýakynda gözlenenler taryhy',
    youAreAdmin: 'Siz administrator',
    youHavePremium: 'Sizde işjeň premium abunaçylyk',
    expires: 'gutaraýar',
    dictionaryNameRequired: 'Sözlük ady talap edilýär',
    dictionaryCreated: 'Sözlük üstünlikli döredildi',
    dictionaryUpdated: 'Sözlük üstünlikli täzelendi',
    dictionaryDeleted: 'Sözlük üstünlikli öçürildi',
    dictionaryFromSelected: 'Saýlanan sözlerden sözlük döredildi!',
    failedCreateDictionary: 'Sözlük döretmek başa barmady',
    noWordsSelected: 'Hiç hili söz saýlanmady',
    enterDictionaryName: 'Sözlük adyny giriziň:',

    // Админ панель
    confirmDeleteUser: 'Bu ulanyjyny pozmak isleýändigiňize ynanýarsyňyzmy?',
    promptBanReason: 'Blokirleme sebäbini giriziň:',
    userUpdated: 'Ulanyjy üstünlikli täzelendi',
    failedUpdateUser: 'Ulanyjyny täzelemek başa barmady',
    failedDeleteUser: 'Ulanyjyny pozmak başa barmady',
    userBanned: 'Ulanyjy blokirlenildi',
    failedBanUser: 'Ulanyjyny blokirlemek başa barmady',
    userUnbanned: 'Ulanyjy blokirlenmeden aýryldy',
    failedUnbanUser: 'Ulanyjyny blokirlenmeden aýyrmak başa barmady',
    unknown: 'Näbelli',
    loadingText: 'Ýüklenýär...',

    // Компонент SearchResults
    noResultsFound: 'Tapylmady üçin',
    foundResults: 'Tapyldy',
    results: 'netije',
    addToSelected: 'Saýlananlara goş',
    viewDetails: 'Jikme-jiklik',
    addToSelectedWords: 'Saýlanan sözlere goş',
    definition: 'Kesgitleme',
    strokeOrder: 'Çyzgy tertibi',
    exampleSentences: 'Mysal sözlemler',
    loadingStrokeOrder: 'Çyzgy tertibini ýüklenýär...',
    strokeOrderNotAvailable: 'Çyzgy tertibi animasiýasy elýeter däl',
    playPronunciation: 'Aýdyň oka',
    loadingExamples: 'Mysallary ýüklenýär...',
    noExamplesFound: 'Mysal sözlemler tapylmady',
    exampleSentencesTitle: 'Mysal sözlemler',
    premium: 'PREMIÝA',
    free: 'MUGT',
    showAllExamples: 'Ähli {count} mysaly görkez ({more} sany köp)',
    showLess: 'Az görkez',
    tryDifferentSearch: 'Başga nyşanlar, pinyin ýa-da iňlis sözleri bilen gözläň',
    traditional: 'Köneş:',
    loadingPinyin: 'Ýüklenýär...',
    wordAddedToSelected: 'Söz saýlananlara goşuldy!',
    failedToAddWord: 'Söz goşup bolmady'
  },
  zh: {
    // Навигация
    learn: '学习',
    dictionary: '词典',
    myDictionaries: '我的词典',
    search: '搜索',
    lexiconNav: 'HSK',
    lexiconTitle: 'HSK词库',
    lexiconSubtitle: '官方HSK 1–6词汇 — 从基础到进阶',
    lexiconWords: '词',
    lexiconPlaceholder: '汉字、拼音或释义…',
    lexiconFind: '查找',
    lexiconAllLevels: '全部等级',
    lexiconFound: '共 {count} 词',
    lexiconKnown: '已掌握',
    lexiconMarkKnown: '标记为已掌握',
    lexiconHighlightUnique: '高亮生字',
    lexiconHideKnown: '隐藏已掌握',
    lexiconGridHint: '点击查看详情 · 右键标记已掌握',
    translate: '翻译',
    settings: '设置',
    profile: '个人资料',
    adminPanel: '管理面板',
    logout: '退出',
    login: '登录',

    // Лендинг
    appName: '好好学习: Chinese Language',
    heroTitle: '好好学习',
    heroSubtitle: 'Chinese Language — 认真学 HSK，节奏自己定',
    heroDescription: 'HSK 1–6 词库、个人词表、每日目标与进度，专为系统学习打造。',
    productTagline: 'Chinese Language',
    startLearning: '开始学习',
    freeRegister: '注册',
    features: '功能特点',
    hskVocabulary: 'HSK 1-6 词汇',
    hskVocabularyDesc: '包含所有HSK等级的完整词汇表，从入门到高级',
    smartLearning: '智能学习',
    smartLearningDesc: '多种学习模式：汉字-拼音、拼音-汉字、汉字-翻译',
    customDictionary: '自定义词典',
    customDictionaryDesc: '创建自己的词汇表，按需学习',
    learningProgress: '学习进度',
    learningProgressDesc: '跟踪学习进度，查看错题回顾',
    dictionarySearch: '词典搜索',
    dictionarySearchDesc: '快速搜索任何汉字、拼音或翻译',
    keyboardSupport: '快捷键支持',
    keyboardSupportDesc: '使用键盘快速答题，提高效率',
    hotkeysMetaKeys: '1–4 / 空格',
    hotkeysMetaLabel: '快捷键',
    hotkeysAnswers: '选答案',
    hotkeysSkip: '跳过',
    hotkeysEnd: '结束',
    dashToday: '今日',
    dashCards: '张卡片',
    dashStreak: '连续',
    dashBest: '最佳',
    dashAccuracy: '正确率',
    dashSessions: '练习次数',
    dashAnswered: '已答题',
    dashWeek: '近7天',
    dashReviewMistakes: '复习错题',
    dashRecent: '最近词库',
    dashDailyGoal: '每日目标（张）',
    dashSubtitle: '每日练习与进度',
    dashQuickHsk: '快速 HSK（20词）',
    dashBackToHome: '返回主页',
    dashNoMistakes: '暂无错题',
    sessionComplete: '本轮完成',
    sessionCorrect: '正确',
    sessionWrong: '错误',
    sessionTotal: '总计',
    sessionRetry: '再练一次',
    sessionRetryWrong: '重做错题',
    sessionHome: '返回',
    sessionMistakes: '错题',
    showTranslation: '显示释义',
    showPinyin: '显示拼音',
    gradeGreat: '太棒了',
    gradeGood: '不错',
    gradeOk: '继续加油',
    gradeRetry: '建议复习',
    productTagline: 'Chinese Language',
    dictionaryEmpty: '词典没有单词',
    pleaseLogin: '请先登录',
    noWordsInSelection: '所选词库没有单词',
    more: '更多',
    accountHubSub: '账户与偏好',
    accountProfileHint: '姓名与密码',
    accountDictsHint: '你的词表与牌组',
    accountSettingsHint: '主题、语言与偏好',
    accountAdminHint: '用户与管理',
    backToAccount: '账户',
    studyStats: '学习统计',
    exportKnown: '导出已掌握',
    clearKnown: '清空已掌握',
    readyToStart: '准备好开始学习了吗？',
    joinUs: '加入我们，开始你的汉语学习之旅',
    vocabulary: '词汇量',
    hskLevels: 'HSK等级',
    learningModes: '学习模式',
    unlimitedDictionaries: '无限词典',

    // Словари
    words: '词',
    createNewDictionary: '创建新词典',
    importDictionary: '导入词典',
    exportAsJSON: 'JSON导出',
    exportAsCSV: 'CSV导出',
    editDictionary: '编辑词典',
    deleteDictionary: '删除词典',
    startLearningDict: '开始学习',
    actions: '操作',
    selectedWords: '已选词汇',
    clearAll: '清空全部',
    createFromSelected: '从已选创建',
    noDictionariesYet: '暂无词典',
    createYourFirst: '创建你的第一个词典或搜索词汇添加。',
    goToSearch: '前往搜索',
    dictionaryName: '词典名称',

    // Настройки
    themeColor: '主题颜色',
    language: '语言',
    translationLanguages: '显示翻译语言',
    selectTranslations: '选择查看词汇详情时显示的翻译语言',
    selectTranslationsDescription: '选择查看词汇详情时显示的翻译语言',
    save: '保存',
    cancel: '取消',
    settingsSaved: '设置已保存！',
    redirecting: '正在重定向...',

    // Обучение
    correct: '正确',
    incorrect: '错误',
    finish: '完成',
    tryAgain: '重新开始',
    retryIncorrect: '重试错题',
    selectDictionary: '选择词典',
    learningMode: '学习模式',

    // Поиск
    loading: '加载中...',
    searching: '搜索中.. .',
    noResults: '没有找到结果',
    searchPlaceholder: '搜索汉字、拼音或翻译...',
    found: '找到',
    results: '个结果',
    addToSelected: '添加到已选',
    viewDetails: '查看详情',

    // Общее
    home: '首页',
    and: '和',
    more: '更多',

    // Импорт
    format: '格式',
    uploadFile: '上传文件',
    orPasteContent: '或粘贴内容',
    import: '导入',
    jsonFormat: 'JSON格式',
    csvFormat: 'CSV格式',
    copy: '复制',

    // Слово деталь
    definition: '释义',
    strokeOrder: '笔画顺序',
    exampleSentences: '例句',
    loadingStrokeOrder: '正在加载笔画顺序...',
    strokeOrderNotAvailable: '笔画顺序动画不可用',
    playPronunciation: '播放发音',
    loadingExamples: '正在加载例句...',
    noExamplesFound: '未找到例句',
    exampleSentencesTitle: '例句',
    premium: '高级版',
    free: '免费版',
    showAllExamples: '显示全部 {count} 个例句 (还有 {more} 个)',
    showLess: '显示更少',
    traditional: '繁体字：',
    wordAddedToSelected: '单词已添加到已选！',
    failedToAddWord: '添加单词失败',
    tryDifferentSearch: '尝试搜索不同的汉字、拼音或英文单词',

    // Страница Learn/SettingsForm
    learningMode: '学习模式',
    proTip: '小提示：您可以创建自己的自定义词典！',
    goToMyDictionaries: '前往我的词典',
    selectVocabulary: '选择词汇表（所有词汇表互不包含）',
    wordsLimit: '词汇数量限制（0 = 不限制）',
    modesDescription: '模式（如果选择多个，将随机切换）',
    charactersToPinyin: '根据汉字选择拼音',
    pinyinToCharacters: '根据拼音选择汉字',
    charactersToTranslation: '根据汉字选择翻译',
    translationToCharacters: '根据翻译选择汉字',
    otherSettings: '其他设置',
    alwaysShowPinyin: '始终显示拼音',
    alwaysShowDefinition: '始终显示释义',
    loadingDictionaries: '正在加载词典...',
    dictionaryOrder: '词典顺序（拖拽重新排序）：',
    dictionaryNotFound: '词典未找到或为空',
    backToDictionaries: '返回词典',
    learning: '学习：',
    wordsCount: '词',
    confirmDeleteDictionary: '您确定要删除此词典吗？',
    dictionaryExported: '词典 "{name}" 已导出为 {format}',
    pleasePasteOrUpload: '请粘贴或上传文件内容',
    invalidJsonFormat: 'JSON格式无效。应为 { name, words } 或单词数组。',
    noValidWordsFound: '文件中未找到有效的单词',
    importSuccess: '成功导入 {count} 个单词！',
    failedToParseFile: '解析文件失败。请检查格式。',
    andMore: '... 还有 {count} 个',
    failedToClearSelected: '清除选定单词失败：',
    editDictionaryTitle: '编辑词典：{name}',
    wordsLabel: '单词',
    chineseCharacter: '汉字',
    pinyinLabel: '拼音',
    translationLabel: '翻译',
    addWord: '添加单词',
    updateDictionary: '更新词典',
    importDictionaryTitle: '导入词典',
    formatLabel: '格式',
    uploadFile: '上传文件',
    orPasteContent: '或粘贴内容',
    importDictionaryBtn: '导入词典',
    cancel: '取消',
    jsonFormatLabel: 'JSON格式：',
    jsonExampleCopied: 'JSON示例已复制！',
    copy: '📋 复制',
    csvFormatLabel: 'CSV格式：',
    csvExampleCopied: 'CSV示例已复制！',
    dictionaryNamePlaceholder: '我的汉语单词',
    yourNamePlaceholder: '您的姓名',

    // Страница Dictionary
    selectVocabularyList: '选择词汇表',

    // Страница Search
    searchPlaceholder: '搜索汉字、拼音或翻译...',

    // Страница Translate
    textTranslator: '文本翻译',
    from: '从',
    to: '到',
    chinese: '中文',
    russian: '俄语',
    english: '英语',
    turkmen: '土库曼语',
    enterTextToTranslate: '输入要翻译的文本...',
    translationWillAppear: '翻译将显示在这里...',
    useAITranslation: '使用AI翻译（默认）',

    // Системные уведомления
    passwordChanged: '密码修改成功',
    nameChanged: '姓名修改成功',
    settingsSaved: '设置已保存！',
    error: '错误',
    success: '成功',
    somethingWentWrong: '出了点问题',
    pleaseWait: '请稍候...',
    saved: '已保存',
    deleted: '已删除',
    created: '已创建',
    updated: '已更新',
    copied: '已复制！',
    failed: '失败',

    // Страница профиля
    profileSettings: '个人资料设置',
    name: '姓名',
    email: '邮箱',
    profileInformation: '个人资料信息',
    updateProfile: '更新个人资料',
    updating: '更新中...',
    changePassword: '修改密码',
    changing: '修改中...',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
    recentSearchHistory: '最近搜索历史',
    youAreAdmin: '您是管理员',
    youHavePremium: '您有活跃的Premium订阅',
    expires: '到期',
    dictionaryNameRequired: '词典名称为必填项',
    dictionaryCreated: '词典创建成功',
    dictionaryUpdated: '词典更新成功',
    dictionaryDeleted: '词典删除成功',
    dictionaryFromSelected: '从选定词汇创建词典成功！',
    failedCreateDictionary: '创建词典失败',
    noWordsSelected: '未选择任何词汇',
    enterDictionaryName: '输入词典名称：',

    // Админ панель
    confirmDeleteUser: '您确定要删除此用户吗？',
    promptBanReason: '输入封禁原因：',
    userUpdated: '用户更新成功',
    failedUpdateUser: '更新用户失败',
    failedDeleteUser: '删除用户失败',
    userBanned: '用户已被封禁',
    failedBanUser: '封禁用户失败',
    userUnbanned: '用户已解封',
    failedUnbanUser: '解封用户失败',
    unknown: '未知',
    loadingText: '加载中...',

    // Компонент SearchResults
    noResultsFound: '未找到结果',
    foundResults: '找到',
    results: '个结果',
    addToSelected: '添加到已选',
    viewDetails: '查看详情',
    addToSelectedWords: '添加到已选词汇',
    definition: '释义',
    strokeOrder: '笔画顺序',
    exampleSentences: '例句',
    loadingStrokeOrder: '正在加载笔画顺序...',
    strokeOrderNotAvailable: '笔画顺序动画不可用',
    playPronunciation: '播放发音',
    loadingExamples: '正在加载例句...',
    noExamplesFound: '未找到例句',
    exampleSentencesTitle: '例句',
    premium: '高级版',
    free: '免费版',
    showAllExamples: '显示全部 {count} 个例句 (还有 {more} 个)',
    showLess: '显示更少',
    tryDifferentSearch: '尝试搜索不同的汉字、拼音或英文单词',
    traditional: '繁体字：',
    loadingPinyin: '加载中...',
    wordAddedToSelected: '单词已添加到已选！',
    failedToAddWord: '添加单词失败'
  }
}

function applyThemeToDocument(themeKey) {
  if (typeof document === 'undefined') return

  const color = THEME_COLORS[themeKey] || THEME_COLORS.blue
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(color)
  const r = result ? parseInt(result[1], 16) : 0
  const g = result ? parseInt(result[2], 16) : 122
  const b = result ? parseInt(result[3], 16) : 255
  const rgb = `${r}, ${g}, ${b}`
  // WCAG-ish luminance — light accents get dark label text
  const lum = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
  const onAccent = lum > 0.62 ? '#0a0a0a' : '#ffffff'

  const root = document.documentElement
  root.style.setProperty('--theme-color', color)
  root.style.setProperty('--theme-color-rgb', rgb)
  root.style.setProperty('--accent', color)
  root.style.setProperty('--on-accent', onAccent)
  root.style.setProperty('--accent-soft', `rgba(${rgb}, 0.16)`)
  root.style.setProperty('--accent-glow', `rgba(${rgb}, 0.35)`)
  root.style.setProperty('--body-glow', `rgba(${rgb}, 0.1)`)
  root.setAttribute('data-theme', themeKey)
}

export function SettingsProvider({ children }) {
  const { user } = useAuth()
  // Keep SSR default stable; real color is restored from localStorage/API on client
  const [themeColor, setThemeColor] = useState('blue')
  const [language, setLanguage] = useState('en')
  const [translationLanguages, setTranslationLanguages] = useState(['en'])
  const [alwaysShowPinyin, setAlwaysShowPinyin] = useState(false)
  const [alwaysShowTranslation, setAlwaysShowTranslation] = useState(false)
  const [loaded, setLoaded] = useState(false)

  // Загрузка настроек из localStorage или API
  useEffect(() => {
    const loadSettings = async () => {
      // Сначала проверяем localStorage
      const savedTheme = localStorage.getItem('themeColor')
      const savedLang = localStorage.getItem('language')
      const savedTransLangs = localStorage.getItem('translationLanguages')
      const savedAlwaysShowPinyin = localStorage.getItem('alwaysShowPinyin')
      const savedAlwaysShowTranslation = localStorage.getItem('alwaysShowTranslation')

      if (savedTheme && THEME_COLORS[savedTheme]) setThemeColor(savedTheme)
      if (savedLang) setLanguage(savedLang)
      if (savedTransLangs) {
        try {
          setTranslationLanguages(JSON.parse(savedTransLangs))
        } catch (e) {}
      }
      if (savedAlwaysShowPinyin) setAlwaysShowPinyin(JSON.parse(savedAlwaysShowPinyin))
      if (savedAlwaysShowTranslation) setAlwaysShowTranslation(JSON.parse(savedAlwaysShowTranslation))

      // Если пользователь авторизован, загружаем с сервера
      if (user) {
        try {
          const response = await axios.get('/api/user/settings')
          if (response.data.settings) {
            const s = response.data.settings
            if (s.themeColor && THEME_COLORS[s.themeColor]) setThemeColor(s.themeColor)
            if (s.language) setLanguage(s.language)
            if (s.translationLanguages) setTranslationLanguages(s.translationLanguages)
            if (s.alwaysShowPinyin !== undefined) setAlwaysShowPinyin(s.alwaysShowPinyin)
            if (s.alwaysShowTranslation !== undefined) setAlwaysShowTranslation(s.alwaysShowTranslation)
          }
        } catch (error) {
          console.error('Failed to load settings:', error)
        }
      }

      setLoaded(true)
    }

    loadSettings()
  }, [user])

  // Применение темы ко всему сайту через CSS-переменные
  useEffect(() => {
    applyThemeToDocument(themeColor)
    if (loaded) {
      localStorage.setItem('themeColor', themeColor)
    }
  }, [themeColor, loaded])

  // Сохранение языка
  useEffect(() => {
    if (!loaded) return
    localStorage.setItem('language', language)
  }, [language, loaded])

  // Сохранение языков перевода
  useEffect(() => {
    if (!loaded) return
    localStorage.setItem('translationLanguages', JSON.stringify(translationLanguages))
  }, [translationLanguages, loaded])

  // Сохранение настроек обучения
  useEffect(() => {
    if (!loaded) return
    localStorage.setItem('alwaysShowPinyin', JSON.stringify(alwaysShowPinyin))
  }, [alwaysShowPinyin, loaded])

  useEffect(() => {
    if (!loaded) return
    localStorage.setItem('alwaysShowTranslation', JSON.stringify(alwaysShowTranslation))
  }, [alwaysShowTranslation, loaded])

  // Функция сохранения на сервер
  const saveSettings = async () => {
    if (!user) return

    try {
      await axios.put('/api/user/settings', {
        themeColor,
        language,
        translationLanguages,
        alwaysShowPinyin,
        alwaysShowTranslation
      })
    } catch (error) {
      console.error('Failed to save settings:', error)
    }
  }

  // Функция для получения названия цвета на текущем языке
  const getColorName = (colorKey, lang) => {
    return THEME_COLOR_NAMES[lang]?.[colorKey] || THEME_COLOR_NAMES.en[colorKey] || colorKey
  }

  // Функция перевода
  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key
  }

  const value = {
    themeColor,
    setThemeColor,
    language,
    setLanguage,
    translationLanguages,
    setTranslationLanguages,
    alwaysShowPinyin,
    setAlwaysShowPinyin,
    alwaysShowTranslation,
    setAlwaysShowTranslation,
    saveSettings,
    t,
    getColorName,
    THEME_COLORS,
    THEME_COLOR_NAMES,
    LANGUAGES
  }

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  )
}

export function useSettings() {
  const context = useContext(SettingsContext)
  if (!context) {
    throw new Error('useSettings must be used within SettingsProvider')
  }
  return context
}